
export const CardsEmployees = [
    {
       _id: 1,
       img: "https://res.cloudinary.com/dnweqtuch/image/upload/v1724450231/ContentImagesJhass/cedqvp85sj2a5qs9upkm.png",
       nombre: 'Johan Cardenas',
       nombreCompleto: 'Johan Sebastian Agudelo',
       correo: 'Johansac@gmail.com',
       telefono: '3104983199',
       rol: 'Super Admin',
       Trabajadas: '176 horas',
       Ausencias: '16 horas',
       Vacaciones: '1 mes',
       descripcion: 'descripcion 1',
       fecha: '20/08/2024'   },
    {
       _id: 2,
       img: "https://res.cloudinary.com/dnweqtuch/image/upload/v1724450231/ContentImagesJhass/cedqvp85sj2a5qs9upkm.png",
       nombre: 'Esteban Cifuente',
       nombreCompleto: 'Esteban Cifuente',
       correo: 'esteban@gmail.com',
       telefono: '3104983198',
       rol: 'Gerente',
       Trabajadas: '176 horas',
       Ausencias: '16 horas',
       Vacaciones: '1 mes',
       descripcion: 'Anomalia en la seccion b',
       fecha: '19/08/2024',
    },
    {
       _id: 3,
       img: "https://res.cloudinary.com/dnweqtuch/image/upload/v1724450231/ContentImagesJhass/cedqvp85sj2a5qs9upkm.png",
       nombre: 'Ana Gomez',
       nombreCompleto: 'Ana Patricia Gomez',
       correo: 'ana.gomez@gmail.com',
       telefono: '3104983197',
       rol: 'Supervisor',
       Trabajadas: '180 horas',
       Ausencias: '8 horas',
       Vacaciones: '2 semanas',
       descripcion: 'Anomalia en la seccion b',
       fecha: '19/08/2024',
    },
    {
       _id: 4,
       img: "https://res.cloudinary.com/dnweqtuch/image/upload/v1724450231/ContentImagesJhass/cedqvp85sj2a5qs9upkm.png",
       nombre: 'Carlos Perez',
       nombreCompleto: 'Carlos Alberto Perez',
       correo: 'carlos.perez@gmail.com',
       telefono: '3104983196',
       rol: 'Empleado',
       Trabajadas: '170 horas',
       Ausencias: '20 horas',
       Vacaciones: '3 semanas',
       descripcion: 'Anomalia en la seccion b',
       fecha: '19/08/2024',
    },
    {
       _id: 5,
       img: "https://res.cloudinary.com/dnweqtuch/image/upload/v1724450231/ContentImagesJhass/cedqvp85sj2a5qs9upkm.png",
       nombre: 'Lucia Martinez',
       nombreCompleto: 'Lucia Fernanda Martinez',
       correo: 'lucia.martinez@gmail.com',
       telefono: '3104983195',
       rol: 'Empleado',
       Trabajadas: '160 horas',
       Ausencias: '10 horas',
       Vacaciones: '1 mes',
       descripcion: 'Anomalia en la seccion b',
       fecha: '19/08/2024',
    },
    {
       _id: 6,
       img: "https://res.cloudinary.com/dnweqtuch/image/upload/v1724450231/ContentImagesJhass/cedqvp85sj2a5qs9upkm.png",
       nombre: 'Miguel Rodriguez',
       nombreCompleto: 'Miguel Angel Rodriguez',
       correo: 'miguel.rodriguez@gmail.com',
       telefono: '3104983194',
       rol: 'Supervisor',
       Trabajadas: '165 horas',
       Ausencias: '15 horas',
       Vacaciones: '2 semanas',
       descripcion: 'Anomalia en la seccion b',
       fecha: '19/08/2024',
    },
    {
       _id: 7,
       img: "https://res.cloudinary.com/dnweqtuch/image/upload/v1724450231/ContentImagesJhass/cedqvp85sj2a5qs9upkm.png",
       nombre: 'Sofia Hernandez',
       nombreCompleto: 'Sofia Maria Hernandez',
       correo: 'sofia.hernandez@gmail.com',
       telefono: '3104983193',
       rol: 'Administrador',
       Trabajadas: '175 horas',
       Ausencias: '12 horas',
       Vacaciones: '1 mes',
       descripcion: 'Anomalia en la seccion b',
       fecha: '19/08/2024',
    },
    {
       _id: 8,
       img: "https://res.cloudinary.com/dnweqtuch/image/upload/v1724450231/ContentImagesJhass/cedqvp85sj2a5qs9upkm.png",
       nombre: 'Andres Lopez',
       nombreCompleto: 'Andres Felipe Lopez',
       correo: 'andres.lopez@gmail.com',
       telefono: '3104983192',
       rol: 'Administrador',
       Trabajadas: '185 horas',
       Ausencias: '5 horas',
       Vacaciones: '3 semanas',
       descripcion: 'Anomalia en la seccion b',
       fecha: '19/08/2024',
    },
    {
       _id: 9,
       img: "https://res.cloudinary.com/dnweqtuch/image/upload/v1724450231/ContentImagesJhass/cedqvp85sj2a5qs9upkm.png",
       nombre: 'Mariana Diaz',
       nombreCompleto: 'Mariana Sofia Diaz',
       correo: 'mariana.diaz@gmail.com',
       telefono: '3104983191',
       rol: 'Supervisor',
       Trabajadas: '190 horas',
       Ausencias: '3 horas',
       Vacaciones: '2 semanas',
       descripcion: 'Anomalia en la seccion b',
       fecha: '19/08/2024',
    },
    {
       _id: 10,
       img: "https://res.cloudinary.com/dnweqtuch/image/upload/v1724450231/ContentImagesJhass/cedqvp85sj2a5qs9upkm.png",
       nombre: 'Pedro Ramirez',
       nombreCompleto: 'Pedro Andres Ramirez',
       correo: 'pedro.ramirez@gmail.com',
       telefono: '3104983190',
       rol: 'Empleador',
       Trabajadas: '180 horas',
       Ausencias: '7 horas',
       Vacaciones: '1 mes',
       descripcion: 'Anomalia en la seccion e',
       fecha: '19/08/2024',
    },
 
 ];
 